	.align 2
voicegroup602::
	voice_directsound 80, 0, DirectSoundSynth_golden_sun_2_04, 255, 235, 103, 178 @ 0 | Direct | GS2 Synth
	voice_directsound 80, 0, DirectSoundSynth_golden_sun_2_05, 255, 235, 103, 165 @ 1 | Direct | GS2 Synth
	voice_directsound 80, 0, DirectSoundSynth_golden_sun_2_01, 255, 127, 90, 165 @ 2 | Direct | GS2 Synth
	voice_directsound 80, 0, DirectSoundSynth_golden_sun_2_01, 255, 127, 90, 165 @ 3 | Direct | GS2 Synth
	voice_directsound 80, 0, DirectSoundSynth_golden_sun_2_03, 255, 127, 90, 165 @ 4 | Direct | GS2 Synth
	voice_directsound 80, 0, DirectSoundSynth_golden_sun_2_04, 255, 127, 90, 165 @ 5 | Direct | GS2 Synth
	voice_directsound 80, 0, DirectSoundSynth_golden_sun_2_05, 255, 127, 103, 165 @ 6 | Direct | GS2 Synth
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 7, 0 @ 7 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 1, 7, 0 @ 8 | Square-2 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 9 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 10 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 11 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_xylophone, 255, 235, 103, 178 @ 12 | Direct | GS2 Xylophone / Gamelan
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_indian_raag_effect, 255, 242, 103, 178 @ 13 | Direct | GS2 Indian Raag Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_wood_block, 255, 0, 255, 165 @ 14 | Direct | GS2 Wood Block
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_woh_voice_effect, 255, 0, 255, 165 @ 15 | Direct | GS2 Woh Voice Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_asian_gamelan_part1, 255, 0, 255, 165 @ 16 | Direct | GS2 Gamelan Part 1
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_asian_gamelan_part2, 255, 235, 103, 178 @ 17 | Direct | GS2 Gamelan Part 2
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_indian_sarod, 255, 0, 255, 165 @ 18 | Direct | GS2 Indian Sarod
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_beat_loop1, 255, 0, 255, 165 @ 19 | Direct | GS2 Drum Beat Loop
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_beat_loop2, 255, 0, 255, 165 @ 20 | Direct | GS2 Jungle Beat Loop
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_tropical_piano, 255, 235, 103, 178 @ 21 | Direct | GS2 Tropical Piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 22 | Square-1 | --
	voice_directsound 80, 0, DirectSoundWaveData_golden_sun_2_taiko, 255, 0, 255, 0 @ 23 | Direct | GS2 Taiko?
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 24 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 25 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 26 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 27 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 28 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 29 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 30 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 31 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 32 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 33 | Square-1 | --
	voice_keysplit_all voicegroup602 @ 34 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_conga, 255, 0, 255, 165 @ 35 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_rnd_kick, 255, 0, 255, 216 @ 36 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_rim, 255, 0, 255, 165 @ 37 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_snare, 255, 0, 255, 216 @ 38 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_handclap, 255, 0, 255, 216 @ 39 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_kick, 255, 0, 255, 216 @ 40 | Direct |
	voice_directsound 50, 0, DirectSoundWaveData_golden_sun_2_tom, 255, 0, 255, 216 @ 41 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_ride_cymbal, 128, 0, 255, 216 @ 42 | Direct |
	voice_directsound 55, 0, DirectSoundWaveData_golden_sun_2_tom, 255, 0, 255, 216 @ 43 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_tom, 255, 0, 255, 216 @ 44 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_tom, 255, 0, 255, 216 @ 45 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_close_hihat, 255, 0, 255, 165 @ 46 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_tom, 255, 0, 255, 216 @ 47 | Direct |
	voice_directsound 65, 0, DirectSoundWaveData_golden_sun_2_tom, 255, 0, 255, 216 @ 48 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_cymbal_crash, 255, 252, 0, 165 @ 49 | Direct |
	voice_directsound 70, 0, DirectSoundWaveData_golden_sun_2_tom, 255, 0, 255, 216 @ 50 | Direct |
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_golden_sun_2_open_hihat, 255, 249, 0, 165 @ 51 | Direct |
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 4 @ 52 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 2 @ 53 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 0 @ 54 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 7, 15, 7 @ 55 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 4 @ 56 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 2 @ 57 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 0 @ 58 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 7, 15, 7 @ 59 | Square-2 |
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 9, 4 @ 60 | Square-1 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 61 | Square-1 | --
	voice_square_1_alt 60, 0, 0, 3, 0, 4, 0, 4 @ 62 | Square-1 |
	voice_square_1_alt 60, 0, 0, 3, 0, 4, 0, 2 @ 63 | Square-1 |
	voice_square_1_alt 60, 0, 0, 3, 0, 4, 0, 0 @ 64 | Square-1 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 65 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 68 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 70 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71 | Square-1 | --
	voice_noise_alt 60, 0, 0, 0, 4, 0, 4 @ 72 | Noise |
	voice_noise_alt 60, 0, 0, 0, 4, 0, 2 @ 73 | Noise |
	voice_noise_alt 60, 0, 0, 0, 4, 0, 0 @ 74 | Noise |
	voice_noise_alt 60, 0, 0, 0, 7, 15, 7 @ 75 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76 | Square-1 | --
	voice_noise_alt 60, 0, 1, 0, 4, 0, 4 @ 77 | Noise |
	voice_noise_alt 60, 0, 1, 0, 4, 0, 2 @ 78 | Noise |
	voice_noise_alt 60, 0, 1, 0, 4, 0, 0 @ 79 | Noise |
	voice_noise_alt 60, 0, 1, 0, 7, 15, 7 @ 80 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81 | Square-1 | --
	voice_noise_alt 60, 0, 1, 0, 4, 0, 4 @ 82 | Noise |
	voice_noise_alt 60, 0, 1, 0, 4, 0, 2 @ 83 | Noise |
	voice_noise_alt 60, 0, 1, 0, 4, 0, 0 @ 84 | Noise |
	voice_noise_alt 60, 0, 0, 0, 7, 15, 7 @ 85 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 86 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 88 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 90 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 91 | Square-1 | --
	voice_square_1_alt 60, 0, 0, 2, 1, 6, 0, 6 @ 92 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_GoldenSun2pcm002, 0, 4, 0, 2 @ 93 | Wave |
	voice_noise_alt 60, 0, 0, 2, 7, 10, 7 @ 94 | Noise |
	voice_noise_alt 60, 0, 0, 0, 7, 4, 3 @ 95 | Noise |
	voice_noise_alt 60, 0, 0, 5, 2, 6, 6 @ 96 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 97 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 98 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 99 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 100 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 101 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_unknown_wave, 255, 0, 255, 0 @ 102 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_earthquake_effect, 255, 0, 255, 204 @ 103 | Direct | GS2 Earthquake Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_explosion_effect, 255, 0, 255, 216 @ 104 | Direct | GS2 Explosion Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_psynergy_effect, 255, 0, 255, 216 @ 105 | Direct | GS2 Psynergy Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_monster_cry, 255, 0, 255, 216 @ 106 | Direct | GS2 Monster Cry
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_thunder_effect, 255, 0, 255, 188 @ 107 | Direct | GS2 Thunder Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_gunshot1, 255, 0, 255, 204 @ 108 | Direct | GS2 Gunshot 1
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_gunshot2, 255, 0, 255, 204 @ 109 | Direct | GS2 Gunshot 2
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_crash_down_effect, 255, 0, 255, 204 @ 110 | Direct | GS2 Crash Down Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_triangle, 255, 188, 154, 226 @ 111 | Direct | GS2 Triangle
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 64, 232, 0, 232 @ 112 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 64, 232, 0, 195 @ 113 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 64, 232, 0, 0 @ 114 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 64, 0, 255, 0 @ 115 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 64, 0, 255, 0 @ 116 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 64, 232, 0, 232 @ 117 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 64, 232, 0, 195 @ 118 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 64, 232, 0, 0 @ 119 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 64, 0, 255, 0 @ 120 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 64, 0, 255, 0 @ 121 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 255, 0, 255, 204 @ 122 | Direct | GS2 Synth
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_crystal_effect, 255, 242, 28, 165 @ 123 | Direct | GS2 Crystal
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_applause, 255, 0, 255, 226 @ 124 | Direct | GS2 Applause
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 125 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 126 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 127 | Square-1 | --
