	.align 2
voicegroup701::
	voice_keysplit_all voicegroup002                                                            @ 000 | Direct | Drum | Emerald Drum Kit 2
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_0080A080, 85, 165, 193, 178      @ 001 | Direct | Synth, sound like gunshot
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 002 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 003 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 004 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 005 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 006 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 007 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 008 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 009 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 010 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 011 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 012 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 013 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 014 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 015 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 016 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 017 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 018 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 019 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 020 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 021 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 022 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 023 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 024 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 025 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 026 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 027 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 028 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 029 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 030 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 031 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 032 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 033 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 034 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 035 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 036 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 037 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 038 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 039 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 040 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 041 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 042 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 043 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 044 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 045 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 046 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 047 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 048 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 049 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 050 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 051 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 052 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 053 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 054 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 055 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 056 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 057 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 058 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 059 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 060 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 061 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 062 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 063 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 064 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 065 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 066 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 067 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 068 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 069 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 070 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 071 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 072 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 073 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 074 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 075 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 076 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 077 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 078 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 079 | Blank | 
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_10F0E080, 85, 165, 193, 178      @ 080 | Direct | Synth, Copied ADSR from Golden Sun 2
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_60204080, 85, 165, 193, 178      @ 081 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_80404040, 85, 165, 193, 178      @ 082 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Type_01, 85, 165, 167, 178                    @ 083 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Type_02, 85, 127, 218, 165                    @ 084 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_10F0E080, 22, 165, 193, 195      @ 085 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_60204080, 22, 165, 193, 195      @ 086 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_80404040, 22, 165, 193, 195      @ 087 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Type_01, 22, 165, 167, 195                    @ 088 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Type_02, 22, 127, 218, 165                    @ 089 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_10F0E080, 255, 235, 90, 178      @ 090 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_60204080, 255, 235, 90, 178      @ 091 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_80404040, 255, 235, 90, 178      @ 092 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Type_01, 255, 235, 103, 178                   @ 093 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Type_02, 255, 235, 103, 165                   @ 094 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_10F0E080, 255, 127, 90, 165      @ 095 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_60204080, 255, 127, 90, 165      @ 096 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Custom_Param_80404040, 255, 127, 90, 165      @ 097 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Type_01, 255, 127, 90, 165                    @ 098 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_directsound 60, 0, DirectSoundSynthData_Type_02, 255, 127, 103, 165                   @ 099 | Direct | Synth, Copied ADSR from Golden Sun 2                               
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 100 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 101 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 102 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 103 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 104 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 105 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 106 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 107 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 108 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 109 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 110 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 111 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 112 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 113 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 114 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 115 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 116 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 117 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 118 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 119 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 120 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 121 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 122 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 123 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 124 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 125 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 126 | Blank | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                     @ 127 | Blank | 
