voicegroup601::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 0 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 1 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 2 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 3 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 4 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 5 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 6 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 7 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_celesta, 255, 0, 255, 165                       @ 8 | Direct | GBA Golden Sun Celesta
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 9 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 10 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 11 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 12 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 13 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 14 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 15 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 16 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 17 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 18 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 19 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 20 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 21 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 22 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 23 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_nylon_guitar, 255, 0, 255, 165                  @ 24 | Direct | GBA Golden Sun Nylon Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 25 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 26 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 27 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 28 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 29 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 30 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 31 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 32 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_fingered_bass, 255, 0, 255, 165                 @ 33 | Direct | GBA Golden Sun Fingered Bass
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_GoldenSun2pcm001, 0, 2, 3, 3                      @ 34 | Wave | GBA Programmable Wave GS 1 2, 3, 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 35 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 36 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 37 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 38 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 39 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 40 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 41 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 42 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 43 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 44 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_pizzicato_strings, 255, 0, 255, 165             @ 45 | Direct | GBA Golden Sun Pizzicato Strings
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_harp, 255, 0, 255, 165                          @ 46 | Direct | GBA Golden Sun Harp
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_timpani, 255, 0, 255, 165                       @ 47 | Direct | GBA Golden Sun Timpani
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_string_ensemble, 255, 0, 255, 165               @ 48 | Direct | GBA Golden Sun String Ensemble
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 49 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 50 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 51 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_choir, 255, 0, 255, 165                         @ 52 | Direct | GBA Golden Sun Choir Aahs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 53 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 54 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 55 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_trumpet, 255, 0, 255, 165                       @ 56 | Direct | GBA Golden Sun Trumpet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 57 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 58 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 59 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 60 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_brass, 255, 0, 255, 165                         @ 61 | Direct | GBA Golden Sun Brass Section
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 62 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 63 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 64 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 65 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 66 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 67 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_oboe, 255, 0, 255, 165                          @ 68 | Direct | GBA Golden Sun Oboe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 69 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 70 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 71 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_piccolo, 255, 0, 255, 165                       @ 72 | Direct | GBA Golden Sun Piccolo
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_flute, 255, 0, 255, 165                         @ 73 | Direct | GBA Golden Sun Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 74 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_pan_flute, 255, 0, 255, 165                     @ 75 | Direct | GBA Golden Sun Pan Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 76 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 77 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 78 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 79 | ---
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 85, 165, 193, 178                              @ 80 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 85, 165, 193, 178                              @ 81 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 85, 165, 193, 178                              @ 82 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_04, 85, 165, 167, 178                              @ 83 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_05, 85, 127, 218, 165                              @ 84 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 22, 165, 193, 195                              @ 85 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 22, 165, 193, 195                              @ 86 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 22, 165, 193, 195                              @ 87 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_04, 22, 165, 167, 195                              @ 88 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_05, 22, 127, 218, 165                              @ 89 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 255, 235, 90, 178                              @ 90 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_02, 255, 235, 90, 178                              @ 91 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 255, 235, 90, 178                              @ 92 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_04, 255, 235, 103, 178                             @ 93 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_05, 255, 235, 103, 165                             @ 94 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 255, 127, 90, 165                              @ 95 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_01, 255, 127, 90, 165                              @ 96 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_03, 255, 127, 90, 165                              @ 97 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_04, 255, 127, 90, 165                              @ 98 | Direct | GBA Golden Sun Synt
	voice_directsound 60, 0, DirectSoundSynth_golden_sun_2_05, 255, 127, 103, 165                             @ 99 | Direct | GBA Golden Sun Synt
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 7, 0                                                                @ 100 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 1, 7, 0                                                                   @ 101 | Square-2 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 102 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 103 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 104 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_xylophone, 255, 235, 103, 178                   @ 105 | Direct | GBA Golden Sun Xylophone / Gamelan
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_indian_raag_effect, 255, 242, 103, 178          @ 106 | Direct | GBA Golden Sun Indian Raag Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_wood_block, 255, 0, 255, 165                    @ 107 | Direct | GBA Golden Sun Wood Block
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_woh_voice_effect, 255, 0, 255, 165              @ 108 | Direct | GBA Golden Sun Woh Voice Effect
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_asian_gamelan_part1, 255, 0, 255, 165           @ 109 | Direct | GBA Golden Sun Gamelan Part 1
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_asian_gamelan_part2, 255, 235, 103, 178         @ 110 | Direct | GBA Golden Sun Gamelan Part 2
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_indian_sarod, 255, 0, 255, 165                  @ 111 | Direct | GBA Golden Sun Indian Sarod
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_beat_loop1, 255, 0, 255, 165                    @ 112 | Direct | GBA Golden Sun Drum Beat Loop
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_beat_loop2, 255, 0, 255, 165                    @ 113 | Direct | GBA Golden Sun Jungle Beat Loop
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_tropical_piano, 255, 235, 103, 178              @ 114 | Direct | GBA Golden Sun Tropical Piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 115 | ---
	voice_directsound 80, 0, DirectSoundWaveData_golden_sun_2_taiko, 255, 0, 255, 0                           @ 116 | Direct | GBA Golden Sun Taiko?
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 117 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 118 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 119 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 120 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 121 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 122 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 123 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 124 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 125 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                   @ 126 | ---
	voice_keysplit_all voicegroup602                                                                          @ 127 | Drum | GBA Golden Sun Drum

