	.align 2
voicegroup805::
	voice_keysplit_all voicegroup806                                                      @ 000 | GBA Drum | 
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 13, 2                                           @ 001 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 7, 3, 1                                            @ 002 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 13, 1                                           @ 003 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 3, 0, 0, 13, 2                                           @ 004 | GB Square-1 | 
	voice_square_2_alt 60, 0, 0, 0, 0, 13, 0                                              @ 005 | GB Square-2 | 
	voice_square_2_alt 60, 0, 1, 0, 0, 13, 2                                              @ 006 | GB Square-2 | 
	voice_square_2_alt 60, 0, 2, 0, 0, 10, 4                                              @ 007 | GB Square-2 | 
	voice_square_2_alt 60, 0, 3, 0, 0, 13, 2                                              @ 008 | GB Square-2 | 
	voice_square_2_alt 60, 0, 2, 1, 0, 10, 4                                              @ 009 | GB Square-2 | 
	voice_square_1_alt 60, 0, 0, 1, 1, 0, 10, 4                                           @ 010 | GB Square-1 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_4, 0, 0, 13, 2                @ 011 | GB Wave | GBA Programmable Wave 4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 0, 13, 2                @ 012 | GB Wave | GBA Programmable Wave 5
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 0, 13, 2                @ 013 | GB Wave | GBA Programmable Wave 6
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_7, 0, 0, 15, 0                @ 014 | GB Wave | GBA Programmable Wave 7
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_8, 0, 0, 13, 1                @ 015 | GB Wave | GBA Programmable Wave 8
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 0, 13, 1                @ 016 | GB Wave | GBA Programmable Wave 3
	voice_square_1_alt 60, 0, 0, 3, 0, 7, 3, 1                                            @ 017 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 2, 1, 0, 13, 0                                           @ 018 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 3, 1, 0, 13, 0                                           @ 019 | GB Square-1 | 
	voice_noise_alt 60, 0, 0, 0, 0, 13, 2                                                 @ 020 | GB Noise | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 021 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 022 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 023 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 024 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 025 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 026 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 027 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 028 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 029 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 030 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 031 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 032 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 033 | --- | *
	voice_square_2_alt 60, 0, 3, 0, 0, 15, 0                                              @ 034 | GB Square-2 | 
	voice_directsound 60, 0, DirectSoundSynth_Type_01, 255, 0, 255, 165                   @ 035 | GBA Synth | 
	voice_keysplit voicegroup244, KeySplitTable40                                         @ 036 | Direct | HGSS drawbar organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 037 | --- | *
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188             @ 020 | Direct | GBA Crunch Organ 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 039 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 040 | --- | *
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 0                                           @ 041 | GB Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 042 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 043 | --- | 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188              @ 019 | Direct | GBA Crunch Organ 1
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171    @ 045 | Direct | HGSS Sawtooth
	voice_directsound 60, 0, DirectSoundWaveData_pc_fwpcmh_orchestra_hit, 255, 0, 255, 0  @ 046 | Direct | FwPCMH Orchestral Hit
	voice_keysplit voicegroup248, KeySplitTable41                                                          @ 026 | Direct | Multi | HGSS Martin Guitar
	voice_keysplit voicegroup196, KeySplitTable2                                          @ 048 | Direct | Multi | GBA String
	voice_keysplit voicegroup255, KeySplitTable45                                         @ 049 | Direct | Multi | HGSS String
	voice_keysplit voicegroup251, KeySplitTable41                                                          @ 027 | Direct | Multi | HGSS Clean Guitar
	voice_directsound 60, 0, DirectSoundSynth_Type_02, 255, 165, 255, 178                 @ 051 | GBA Synth | 
	voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 128, 249, 25, 204  @ 052 | Direct | GBA Trinity Mega Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 053 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 054 | --- | 
	voice_square_1_alt 60, 0, 0x1E, 1, 0, 0, 15, 0                                        @ 055 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0x17, 2, 0, 0, 15, 0                                        @ 056 | GB Square-1 | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_9, 0, 0, 15, 0                @ 057 | GB Wave | GBA Programmable Wave 9
	voice_noise_alt 60, 0, 1, 0, 0, 15, 0                                                 @ 058 | GB Noise | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 060 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 061 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 062 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 063 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 064 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | --- | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_10, 0, 5, 4, 1                @ 070 | GB Wave | GBA Programmable Wave 10
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_11, 0, 5, 4, 1                @ 071 | GB Wave | GBA Programmable Wave 11
	voice_square_2_alt 60, 0, 2, 0, 3, 11, 1                                              @ 072 | GB Square-2 | 
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 11, 1                                           @ 073 | GB Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | --- | 
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_12, 0, 5, 4, 1                @ 080 | GB Wave | GBA Programmable Wave 12
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_13, 0, 3, 12, 1               @ 081 | GB Wave | GBA Programmable Wave 13
	voice_square_2_alt 60, 0, 3, 0, 1, 11, 1                                              @ 082 | GB Square-2 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 1                                           @ 083 | GB Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 086 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | --- | *
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 088 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | --- | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | --- | *
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0                                           @ 094 | GB Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | --- | **
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 0, 0                                            @ 096 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 0, 0                                            @ 097 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 0, 0                                            @ 098 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0                                           @ 099 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0x1F, 0, 0, 1, 0, 0                                         @ 100 | GB Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | --- | **
	voice_square_1_alt 60, 0, 0x1F, 0, 0, 0, 15, 0                                        @ 102 | GB Square-1 | 
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0                                              @ 103 | GB Square-2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | --- | **
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | --- | **
	voice_noise_alt 60, 0, 0, 0, 2, 0, 0                                                  @ 106 | GB Noise | 
	voice_noise_alt 60, 0, 1, 0, 2, 0, 0                                                  @ 107 | GB Noise | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | --- | **
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | --- | **
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0                                           @ 110 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 2, 0                                            @ 111 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 0, 0                                            @ 112 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0                                           @ 113 | GB Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | --- | **
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 0                                            @ 115 | GB Square-1 | 
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 0                                               @ 116 | GB Square-2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | --- | **
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | --- | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0                                           @ 119 | GB Square-1 | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0                                           @ 120 | GB Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 121 | --- | 
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0                                           @ 122 | GB Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 123 | --- | **
	voice_keysplit_all voicegroup191                                                      @ 124 | Direct | Drum | GBA Drum
	voice_keysplit_all voicegroup192                                                      @ 125 | Direct | Drum | GBA Drum
	voice_keysplit_all voicegroup193                                                      @ 126 | Direct | Drum | GBA Drum
	voice_keysplit_all voicegroup230                                                      @ 127 | Direct | Drum | HGSS Drum
