	.align 2
voicegroup806::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 000 | CnM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 001 | CsM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 002 | DnM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 003 | DsM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 004 | EnM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 005 | FnM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 006 | FsM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 007 | GnM2 | 
	voice_square_1 60, 0, 0, 2, 0, 1, 6, 0                                                                              @ 008 | GsM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 009 | AnM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 010 | AsM2 | 
	voice_programmable_wave 60, 0, ProgrammableWaveData_1, 0, 7, 15, 1                                                  @ 011 | BnM2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 012 | CnM1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 013 | CsM1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 014 | DnM1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 015 | DsM1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 016 | EnM1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 017 | FnM1 | 
	voice_square_2 60, 0, 2, 0, 1, 6, 0                                                                                 @ 018 | FsM1 | 
	voice_programmable_wave 60, 0, ProgrammableWaveData_3, 0, 7, 15, 1                                                  @ 019 | GnM1 | 
	voice_square_1 60, 0, 0, 2, 0, 1, 6, 0                                                                              @ 020 | GsM1 | 
	voice_square_2 60, 0, 3, 0, 1, 6, 0                                                                                 @ 021 | AnM1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 022 | AsM1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 023 | BnM1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 024 | Cn0 | 
	voice_square_1 60, 0, 0, 0, 0, 1, 6, 0                                                                              @ 025 | Cs0 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 026 | Dn0 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 027 | Ds0 | 
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0                             @ 028 | En0 | 
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 255, 165, 154, 127                                @ 029 | Fn0 | 
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 255, 165, 154, 127                                   @ 030 | Fs0 | 
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 165, 206, 127                @ 031 | Gn0 | 
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 206, 127                         @ 032 | Gs0 | 
	voice_directsound 60, 0, DirectSoundWaveData_unknown_snare, 255, 0, 255, 0                                          @ 033 | An0 | 
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 0                              @ 034 | As0 | 
	voice_directsound_no_resample 52, 64, DirectSoundWaveData_mmbn6_drumkit_35, 255, 255, 190, 208                      @ 035 | Bn0 | NC
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242                        @ 036 | Cn1 | 
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_mmbn6_drumkit_37, 255, 255, 190, 208                      @ 037 | Cs1 | 
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242                       @ 038 | Dn1 | VI
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127               @ 039 | Ds1 | 
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 0, 255, 0                                           @ 040 | En1 | NC
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_unknown_close_hihat, 255, 255, 190, 0                     @ 041 | Fn1 |   VI
	voice_noise 0x53, 0, 0, 0, 0, 11, 0                                                                                 @ 042 | Fs1 | NCVI
	voice_directsound 54, 20, DirectSoundWaveData_hg_135tom, 255, 0, 255, 171                                           @ 043 | Gn1 |   VI
	voice_noise 0x4F, 0, 0, 5, 5, 6, 4                                                                                  @ 044 | Gs1 | 
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 255, 120, 0                                         @ 045 | An1 | NC
	voice_noise 0x53, 0, 0, 0, 2, 11, 3                                                                                 @ 046 | As1 | NCVI
	voice_directsound 60, 64, DirectSoundWaveData_hg_135tom, 255, 0, 255, 171                                           @ 047 | Bn1 |   VI
	voice_directsound 66, 108, DirectSoundWaveData_hg_135tom, 255, 0, 255, 171                                          @ 048 | Cn2 |   VI
	voice_noise 0x47, 0, 0, 0, 7, 0, 1                                                                                  @ 049 | Cs2 | NCVI
	voice_directsound 62, 84, DirectSoundWaveData_hg_135tom, 255, 0, 255, 171                                           @ 050 | Dn2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 051 | Ds2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 052 | En2 | 
	voice_directsound_no_resample 70, 49, DirectSoundWaveData_unknown_bell, 255, 165, 103, 231                          @ 053 | Fn2 | 
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 190, 223                 @ 054 | Fs2 | NC
	voice_directsound 60, 84, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 0                                      @ 055 | Gn2 | NC
	voice_directsound 60, 34, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 0                                     @ 056 | Gs2 | NC
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216          @ 057 | An2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 058 | As2 | 
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216          @ 059 | Bn2 | 
	voice_directsound_no_resample 30, 64, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 8, 0, 255, 216            @ 060 | Cn3 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 061 | Cs3 | 
	voice_directsound_no_resample 72, 104, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0                  @ 062 | Dn3 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 063 | Ds3 | 
	voice_directsound_no_resample 72, 94, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0                    @ 064 | En3 | 
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 0                  @ 065 | Fn3 | 
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228                       @ 066 | Fs3 | 
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 0, 255, 242                         @ 067 | Gn3 | 
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127               @ 068 | Gs3 | 
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242                 @ 069 | An3 | 
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                    @ 070 | As3 | 
	voice_directsound_no_resample 64, 80, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242                 @ 071 | Bn3 | 
	voice_directsound 68, 34, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                    @ 072 | Cn4 | 
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_mmbn6_drumkit_35, 26, 0, 255, 0                           @ 073 | Cs4 | NC
	voice_directsound 72, 44, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                    @ 074 | Dn4 | 
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242                       @ 075 | Ds4 | 
	voice_directsound 76, 84, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                    @ 076 | En4 | 
	voice_directsound 80, 94, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                    @ 077 | Fn4 | 
	voice_directsound_no_resample 33, 89, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231          @ 078 | Fs4 | 
	voice_directsound 84, 104, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 235                                   @ 079 | Gn4 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 080 | Gs4 | 
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231                      @ 081 | An4 | 
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_dance_drums_ride_bell, 255, 165, 103, 231                 @ 082 | As4 | 
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204                     @ 083 | Bn4 | 
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188                    @ 084 | Cn5 | 
	voice_directsound_no_resample 64, 89, DirectSoundWaveData_sd90_cowbell, 255, 0, 255, 242                            @ 085 | Cs5 | 
	voice_directsound_no_resample 64, 29, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231          @ 086 | Dn5 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 087 | Ds5 | 
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231          @ 088 | En5 | 
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 8, 0, 255, 216            @ 089 | Fn5 | 
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0          @ 090 | Fs5 | 
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0                   @ 091 | Gn5 | 
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0                    @ 092 | Gs5 | 
	voice_directsound_no_resample 64, 90, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0                    @ 093 | An5 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 094 | As5 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 095 | Bn5 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 096 | Cn6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 097 | Cs6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 098 | Dn6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 099 | Ds6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 100 | En6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 101 | Fn6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 102 | Fs6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 103 | Gn6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 104 | Gs6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 105 | An6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 106 | As6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 107 | Bn6 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 108 | Cn7 | 
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188                    @ 109 | Cs7 | 
	voice_directsound_no_resample 64, 79, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188                    @ 110 | Dn7 | 
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 165, 103, 188                    @ 111 | Ds7 | 
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_sc88pro_jingle_bell, 255, 0, 255, 0                       @ 112 | En7 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 113 | Fn7 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                             @ 114 | Fs7 | 
	voice_directsound_no_resample 64, 104, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0                @ 115 | Gn7 | 
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0                                         @ 116 | Gs7 | 
	voice_directsound 50, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0                             @ 117 | An7 | 
	voice_directsound 64, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0                             @ 118 | As7 | 
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0                             @ 119 | Bn7 | 
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228                       @ 120 | Cn8 | 
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 0, 255, 242                         @ 121 | Cs8 | 
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127               @ 122 | Dn8 | 
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242                 @ 123 | Ds8 | 
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                    @ 124 | En8 | 
	voice_directsound_no_resample 64, 80, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242                 @ 125 | Fn8 | 
	voice_directsound 68, 34, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                    @ 126 | Fs8 | 
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242                       @ 127 | Gn8 | 
