# 1 "data/maps/CitrusIsland_House1/scripts.pory"

# 2 "data/maps/CitrusIsland_House1/scripts.pory"
CitrusIsland_House1_MapScripts::
# 3 "data/maps/CitrusIsland_House1/scripts.pory"
	.byte 0
# 4 "data/maps/CitrusIsland_House1/scripts.pory"

# 5 "data/maps/CitrusIsland_House1/scripts.pory"
CitrusIsland_House1_EventScript_Woman::
# 6 "data/maps/CitrusIsland_House1/scripts.pory"
	msgbox CitrusIsland_House1_Text_KidNeverSaw, MSGBOX_NPC
# 7 "data/maps/CitrusIsland_House1/scripts.pory"
	end
# 8 "data/maps/CitrusIsland_House1/scripts.pory"

# 9 "data/maps/CitrusIsland_House1/scripts.pory"
CitrusIsland_House1_EventScript_LittleBoy::
# 10 "data/maps/CitrusIsland_House1/scripts.pory"
	msgbox CitrusIsland_House1_Text_TheMainland, MSGBOX_NPC
# 11 "data/maps/CitrusIsland_House1/scripts.pory"
	end
# 12 "data/maps/CitrusIsland_House1/scripts.pory"

# 13 "data/maps/CitrusIsland_House1/scripts.pory"
CitrusIsland_House1_Text_KidNeverSaw:
# 14 "data/maps/CitrusIsland_House1/scripts.pory"
	.string "My kid never saw the mainland. I wish\n"
# 15 "data/maps/CitrusIsland_House1/scripts.pory"
	.string "he was able to go on an adventure.$"
# 16 "data/maps/CitrusIsland_House1/scripts.pory"

# 17 "data/maps/CitrusIsland_House1/scripts.pory"
CitrusIsland_House1_Text_TheMainland:
# 18 "data/maps/CitrusIsland_House1/scripts.pory"
	.string "{PLAYER}-ehm, YOUR HIGHNESS, when\n"
# 19 "data/maps/CitrusIsland_House1/scripts.pory"
	.string "will we ever be allowed to leave?$"
