#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_FUUKA,
    SP_NAME_SHINYA,
    SP_NAME_PROF_ZELKOVA,
    SP_NAME_RAKAN,
    SP_NAME_MITSURU,
    SP_NAME_GEN_DNIPRO,
    SP_NAME_SHIRI,
    SP_NAME_BANJO,
    SP_NAME_UNKNOWN,
    SP_NAME_ARC_SOLDIER,
    SP_NAME_ISAMU,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
