DurianTown_House_MapScripts::
	.byte 0


DurianTown_House_Lass::
# 4 "data/maps/DurianTown_House/scripts.pory"
	lock
# 5 "data/maps/DurianTown_House/scripts.pory"
	faceplayer
# 6 "data/maps/DurianTown_House/scripts.pory"
	msgbox DurianTown_House_Lass_Text_0
# 9 "data/maps/DurianTown_House/scripts.pory"
	release
	end


DurianTown_House_Lass_Text_0:
# 6 "data/maps/DurianTown_House/scripts.pory"
	.string "This town may be pretty, but there\n"
	.string "is nothing to do here!\p"
	.string "I wish I had a permit to move to\n"
	.string "WATERMELON CITY instead.$"
