gText_Birch_Welcome::
	.string "Welcome to the ELEMENTAL CONQUEST\n"
	.string "registration terminal.\p"
	.string "Most of your data was pre-compiled.\p"
	.string "You only need to choose your photo\n"
	.string "and name before your application\l"
	.string "becomes official.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "You only need to choose your photo\n"
	.string "and name before your application\l"
	.string "$"

gText_Birch_MainSpeech::
	.string "You only need to choose your photo\n"
	.string "and name before your application\l"
	.string "becomes official.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "I can't see you…$"

gText_Birch_BoyOrGirl::
	.string "Please choose either picture.$"

gText_Birch_WhatsYourName::
	.string "Now, please insert your name.$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "You two will face many adversities\n"
	.string "in your path, your highness.\p"
	.string "But as the JADE HEIRS, it's your\n"
	.string "destiny to reclaim the throne.\p"
	.string "$"

gText_Birch_AreYouReady::
    .string "Your registration has been accepted.\p"
    .string "Congratulations on becoming an official\n"
    .string "POKéMON TRAINER, and a contestant\l"
    .string "in the ELEMENTAL CONQUEST.\p"
	.string "$"
