gText_Birch_Welcome::
	.string "Welcome, your highness.\p"
	.string "It's an honor to meet you.\p"
	.string "I am ZELKOVA, a POKéMON PROFESSOR,\n"
	.string "and loyal retainer to the\l"
	.string "SUMERAGI royal family.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I have been sent to CITRUS ISLAND,”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "To honor your parents' wish, the late\n"
	.string "JADE EMPEROR and EMPRESS, now that you\p"
	.string "two are of age, I will give you two\n"
	.string "POKéMON each, to participate in the\l"
	.string "restored ELEMENTAL CONQUEST.\p"
	.string "You will have to use a fake identity, as\n"
	.string "the UNITED REGIONS' PEACEKEEPING FORCE\l"
	.string "has forbidden you from leaving\p"
	.string "this island and taking part\n"
	.string "in the CONQUEST.\p"
	.string "Let's record your TRAINER CARD."
	.string "$"

gText_Birch_AndYouAre::
	.string "I can't see you…$"

gText_Birch_BoyOrGirl::
	.string "Choose a twin!$"

gText_Birch_WhatsYourName::
	.string "Now, let's record your pseudonym.$"

gText_Birch_SoItsPlayer::
	.string "You will go by {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "You two will face many adversities\n"
	.string "in your path, your highness.\p"
	.string "But as the JADE HEIRS, it's your\n"
	.string "destiny to reclaim the throne.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "$"
