Text_BootUpPC:
	.string "{PLAYER} connected to the\nPHAROS NETWORK.$"

gText_WhichPCShouldBeAccessed::
	.string "Please select your desired service.$"

gText_AccessedSomeonesPC::
	.string "Hosting & Retrieval System selected.$"

gText_StorageSystemOpened::
	.string "Welcome, {PKMN} CODEWEAVER {PLAYER}.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s CODEWEAVER\nFORUM account.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"
