gText_WouldYouLikeToRestYourPkmn::
	.string "Welcome to the POKéMON STATION.\n"
	.string "Looks like you need our help, huh?\p"
	.string "We will fix your POKéMON up\n"
	.string "to full health.\p"
	.string "Are you handing them over or not?$"

gText_IllTakeYourPkmn::
	.string "Ugh, fine. Give me a second.\n"
	.string "This shouldn’t take long... probably.$"

gText_RestoredPkmnToFullHealth::
	.string "Not leaving a tip, huh? Then maybe\n"
	.string "I should keep your POKéMON... ... ...\p"
	.string "...Relax, I was kidding. Mostly.$"

gText_WeHopeToSeeYouAgain::
	.string "We both know you will be back, but...\n"
	.string "try to not get your POKéMON hurt, okay?$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"
