# 1 "data/maps/CitrusIsland_House3/scripts.pory"

# 2 "data/maps/CitrusIsland_House3/scripts.pory"
CitrusIsland_House3_MapScripts::
# 3 "data/maps/CitrusIsland_House3/scripts.pory"
	.byte 0
# 4 "data/maps/CitrusIsland_House3/scripts.pory"

# 5 "data/maps/CitrusIsland_House3/scripts.pory"
CitrusIsland_House3_EventScript_Kunoichi::
# 6 "data/maps/CitrusIsland_House3/scripts.pory"
	msgbox CitrusIsland_House3_Text_WrongSide, MSGBOX_NPC
# 7 "data/maps/CitrusIsland_House3/scripts.pory"
	end
# 8 "data/maps/CitrusIsland_House3/scripts.pory"

# 9 "data/maps/CitrusIsland_House3/scripts.pory"
CitrusIsland_House3_Text_WrongSide:
# 10 "data/maps/CitrusIsland_House3/scripts.pory"
	.string "Tch. I wonder if it was worth it,\n"
# 11 "data/maps/CitrusIsland_House3/scripts.pory"
	.string "being exhiled here just because I\p"
# 12 "data/maps/CitrusIsland_House3/scripts.pory"
	.string "supported the SUMERAGI dynasty…$"
