# 1 "data/maps/CitrusIsland_House2/scripts.pory"

# 2 "data/maps/CitrusIsland_House2/scripts.pory"
CitrusIsland_House2_MapScripts::
# 3 "data/maps/CitrusIsland_House2/scripts.pory"
	.byte 0
# 4 "data/maps/CitrusIsland_House2/scripts.pory"

# 5 "data/maps/CitrusIsland_House2/scripts.pory"
CitrusIsland_House2_EventScript_OldMan::
# 6 "data/maps/CitrusIsland_House2/scripts.pory"
	msgbox CitrusIsland_House2_Text_WifeGrave, MSGBOX_NPC
# 7 "data/maps/CitrusIsland_House2/scripts.pory"
	end
# 8 "data/maps/CitrusIsland_House2/scripts.pory"

# 9 "data/maps/CitrusIsland_House2/scripts.pory"
CitrusIsland_House2_Text_WifeGrave:
# 10 "data/maps/CitrusIsland_House2/scripts.pory"
	.string "I'm fine never seeing my hometown\n"
# 11 "data/maps/CitrusIsland_House2/scripts.pory"
	.string "again. But I wish my wife was able\l"
# 12 "data/maps/CitrusIsland_House2/scripts.pory"
	.string "to be buried there at least…$"
