# 1 "data/maps/CitrusIsland/scripts.pory"

# 2 "data/maps/CitrusIsland/scripts.pory"
CitrusIsland_MapScripts::
# 3 "data/maps/CitrusIsland/scripts.pory"
	.byte 0
# 4 "data/maps/CitrusIsland/scripts.pory"

# 5 "data/maps/CitrusIsland/scripts.pory"
CitrusIsland_EventScript_Samurai::
# 6 "data/maps/CitrusIsland/scripts.pory"
	msgbox CitrusIsland_Text_TrainingInSecret, MSGBOX_NPC
# 7 "data/maps/CitrusIsland/scripts.pory"
	end
# 8 "data/maps/CitrusIsland/scripts.pory"

# 9 "data/maps/CitrusIsland/scripts.pory"
CitrusIsland_EventScript_Girl::
# 10 "data/maps/CitrusIsland/scripts.pory"
	msgbox CitrusIsland_Text_AreYouLeaving, MSGBOX_NPC
# 11 "data/maps/CitrusIsland/scripts.pory"
	end
# 12 "data/maps/CitrusIsland/scripts.pory"

# 13 "data/maps/CitrusIsland/scripts.pory"
CitrusIsland_Text_TrainingInSecret:
# 14 "data/maps/CitrusIsland/scripts.pory"
	.string "Fear not, YOUR HIGHNESS!\n"
# 15 "data/maps/CitrusIsland/scripts.pory"
	.string "All of us have kept training, even\p"
# 16 "data/maps/CitrusIsland/scripts.pory"
	.string "after being sent here! We are\n"
# 17 "data/maps/CitrusIsland/scripts.pory"
	.string "ready to serve you forever!$"
# 18 "data/maps/CitrusIsland/scripts.pory"

# 19 "data/maps/CitrusIsland/scripts.pory"
CitrusIsland_Text_AreYouLeaving:
# 20 "data/maps/CitrusIsland/scripts.pory"
	.string "YOUR HIGHNESS, I have heard you are\n"
# 21 "data/maps/CitrusIsland/scripts.pory"
	.string "leaving for the mainland. Stay safe!$"
